name: Build Native Executables (All Platforms)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [linux-x64, linux-arm64, windows-x64,  macos-x64, macos-arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          ini-values: phar.readonly=0

      - name: Install Composer deps
        run: composer install --no-dev || true

      - name: Build PHAR
        run: |
          php build.php
          ls -lh nova.phar

      - name: Download static-php
        run: |
          curl -fsSL -o spc https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-linux-x86_64
          chmod +x spc

      - name: Build native executable for ${{ matrix.target }}
        run: |
          mkdir -p dist
          ./spc micro:combine nova.phar \
            --target=${{ matrix.target }} \
            --output=dist/nova-${{ matrix.target }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/nova-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
